# Use the official CUDA 12.1 base image with Ubuntu
# FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel
# FROM python:3.12.7

# Install Python and other necessary packages
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN python3 -m pip install --upgrade pip
# Install any Python packages you need (e.g., numpy, torch)
RUN python3 -m pip install torch torchvision torchaudio
# RUN python3 -m pip install transformers accelerate peft trl
# RUN python3 -m pip install git+https://github.com/huggingface/transformers
RUN python3 -m pip install transformers==4.16.3
RUN python3 -m pip install git+https://github.com/huggingface/accelerate
RUN python3 -m pip install git+https://github.com/huggingface/peft
RUN python3 -m pip install git+https://github.com/huggingface/trl
RUN python3 -m pip install flash-attn --no-build-isolation
RUN python3 -m pip install datasets numpy sentencepiece gguf protobuf matplotlib
RUN python3 -m pip install bitsandbytes
RUN python3 -m pip install autoawq
RUN python3 -m pip install liger-kernel-nightly
RUN python3 -m pip install llama-recipes
RUN python3 -m pip install ollama
RUN python3 -m pip install tensorboardX
RUN python3 -m pip install qwen-vl-utils[decord]
# RUN python3 -m pip install pymysql
# RUN python3 -m pip install ollama pandas pymysql

# Optional: Set python3 as default python
# RUN ln -s /usr/bin/python3 /usr/bin/python

# RUN pip install -r requirements.txt
