FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel

# Install Python and other necessary packages
RUN apt-get update && \
    apt-get install -y git libgl1-mesa-glx libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install torch torchvision torchaudio
# RUN python3 -m pip install transformers accelerate peft trl
RUN python3 -m pip install git+https://github.com/huggingface/transformers
RUN python3 -m pip install git+https://github.com/huggingface/accelerate
RUN python3 -m pip install git+https://github.com/huggingface/peft
RUN python3 -m pip install git+https://github.com/huggingface/trl
RUN python3 -m pip install flash-attn --no-build-isolation
RUN python3 -m pip install datasets numpy sentencepiece gguf protobuf matplotlib
RUN python3 -m pip install bitsandbytes
RUN python3 -m pip install liger-kernel
# RUN python3 -m pip install liger-kernel-nightly
RUN python3 -m pip install llama-recipes
RUN python3 -m pip install ollama
RUN python3 -m pip install tensorboard
RUN python3 -m pip install qwen-vl-utils[decord]
# RUN python3 -m pip install pymysql

# Optional: Set python3 as default python
# RUN ln -s /usr/bin/python3 /usr/bin/python

# RUN pip install -r requirements.txt
